
services:
  text:
    build: .
    image: ollama/ollama
    working_dir: /app
    ports:
      - "7099:11434"
    volumes:
      - .:/app
      - /root/.ollama:/root/.ollama
      - ~/.cache:/root/.cache
    environment:
      - GITHUB_TOKEN:$GITHUB_TOKEN
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: 1

  mistral:
    build: .
    image: ollama/ollama
    working_dir: /app
    ports:
      - "11430:11434"
    volumes:
      - .:/app
      - /root/.ollama:/root/.ollama
      - ~/.cache:/root/.cache
    environment:
      - GITHUB_TOKEN:$GITHUB_TOKEN
      - CUDA_VISIBLE_DEVICES=1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: 2
  mixtral:
    build: .
    image: ollama/ollama
    working_dir: /app
    ports:
      - "11431:11434"
    volumes:
      - .:/app
      - /root/.ollama:/root/.ollama
      - ~/.cache:/root/.cache
    environment:
      - GITHUB_TOKEN:$GITHUB_TOKEN
      - CUDA_VISIBLE_DEVICES=2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: 3

  code:
    build: .
    image: ollama/ollama
    working_dir: /app
    ports:
      - "11432:11434"
    volumes:
      - .:/app
      - /root/.ollama:/root/.ollama
      - ~/.cache:/root/.cache
    environment:
      - GITHUB_TOKEN:$GITHUB_TOKEN
      - CUDA_VISIBLE_DEVICES=3
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: 4

  bakllava:
    build: .
    image: ollama/ollama
    working_dir: /app
    ports:
      - "11433:11434"
    volumes:
      - .:/app
      - /root/.ollama:/root/.ollama
      - ~/.cache:/root/.cache
    environment:
      - GITHUB_TOKEN:$GITHUB_TOKEN
      - CUDA_VISIBLE_DEVICES=4

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: 5
