name: Deploy
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Timestamp Variable for image tag
        run: echo "image_tag=$(date +'%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV

      - name: Launch containers using script
        run: ./start_text.sh

      - name: Push the container to GHCR
        run: |
          docker tag ghcr.io/agent-artificial/text_gen:${{env.image_tag}}
